name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mariadbc
        run: sudo apt-get install libmariadb3 -y
        shell: bash
      - name: update ldconfig
        run: touch /etc/ld.so.conf.d/libmariadb.conf && echo "/usr/lib/mariadb/" >> /etc/ld.so.conf.d/libmariadb.conf && ldconfig 
        shell: bash
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest blinker click colorama Flask Flask-Login itsdangerous Jinja2 mariadb MarkupSafe packaging python-dotenv Werkzeug waitress
          pip install . -v
      - name: Test with pytest
        run: |
          pytest

  build-windows:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest blinker click colorama Flask Flask-Login itsdangerous Jinja2 mariadb MarkupSafe packaging python-dotenv Werkzeug waitress
          pip install . -v
      - name: Test with pytest
        run: |
          pytest

  build-macos:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest blinker click colorama Flask Flask-Login itsdangerous Jinja2 mariadb MarkupSafe packaging python-dotenv Werkzeug waitress
          pip install . -v
      - name: Test with pytest
        run: |
          pytest
